### ISSUE TITLE
code

### ISSUE THREAD

**Issue by 01gOlivia** [wassimea/rgb-thermal-fusion#1]
the code is complete?

**Comment by wassimea** [comment]
yes, it is. any particular issue I can help you with?

**Comment by 01gOlivia** [comment]
I am glad to receive your reply. As a beginner, what command should I enter to preliminarily run your code? thanks！



At 2023-12-22 02:17:45, "Wassim El Ahmar" ***@***.***> wrote:

yes, it is. any particular issue I can help you with?

**Comment by wassimea** [comment]
You should setup mmdetection according to their documentation, and then run python3 train.py $PATH_TO_CONFIG$
