### ISSUE TITLE
method problem

### ISSUE THREAD

**Issue by wenshan1212** [wassimea/rgb-thermal-fusion#2]
Hello, I would like to ask if the Conv of the gating mechanism proposed in this paper needs to be trained?

In addition, since the method proposed in this paper cannot be found in the released code, can you give me a hint on how to find the corresponding code location, for example: In which section of code can the gating mechanism be seen?

Thanks

**Comment by wassimea** [comment]
Hello,

Thank you for your interest in our work! Yes, you would have to re-train the gating mechanism if using it for a new model.

The implementation is indeed made public. For Resnet50, you can find it here https://github.com/wassimea/rgb-thermal-fusion/blob/7694ed1ba0ec229e711cee864999601aeef4c588/mmdetection/mmdet/models/backbones/resnet.py#L905
